[tools]
# python is managed by .python-version
uv = "0.5.1"
node = "22.11.0"
bun = "1.1.37"

[env]
_.python.venv = { path = ".venv", create = true }

[settings]
yes = true
idiomatic_version_file_enable_tools = []

[tasks.generate-docs]
run = "cargo test --package typst-docs --lib -- tests::test_docs --exact --nocapture"

[tasks.generate-web]
run = "bun run build"
dir = "./website"

[tasks.generate]
run = [
    "mise run generate-docs",
    "mise run generate-web"
]

[tasks.dev]
run = "bun run dev"
dir = "./website"

[tasks.preview]
run = "bun run preview"
dir = "./website"
