[tools]
rust = "1.83.0"
node = "22.11.0"
bun = "1.1.37"
pinact = "3.1.1"

[settings]
yes = true
idiomatic_version_file_enable_tools = []

[tasks.generate-docs]
run = "cargo run --package typst-docs -- --assets-dir assets --out-file docs.json --base /docs/"

[tasks.generate-web]
depends = ["install-website"]
run = ["bun run build"]
dir = "./website"

[tasks.generate]
run = [
    "mise run generate-docs",
    "mise run generate-web"
]

[tasks.install-website]
run = "bun install --frozen-lockfile"
dir = "./website"

[tasks.dev]
depends = ["install-website"]
run = "bun run dev"
dir = "./website"

[tasks.preview]
depends = ["install-website"]
run = "bun run preview"
dir = "./website"

[tasks.install-textlint]
run = "bun install --frozen-lockfile"

[tasks.textlint-md]
depends = ["install-textlint"]
run = "bun run textlint-md"

[tasks.textlint-md-fix]
depends = ["install-textlint"]
run = "bun run textlint-md:fix"

[tasks.textlint-html]
depends = ["install-textlint"]
run = "bun run textlint-html"
