name: 🐛 誤字・脱字・誤訳の報告や翻訳改善の提案
description: 誤字・脱字・誤訳の報告や翻訳改善を提案するIssueを作成します。
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: 翻訳ドキュメントの改善をご提案いただきありがとうございます。[Issueを作成する前に同様のIssueが既に存在しないかを確認してください。](https://github.com/typst-jp/typst-jp.github.io/issues?q=is%3Aopen)
  - type: textarea
    attributes:
      label: 対象ドキュメント
      description: 翻訳対象のドキュメントを記載してください。
    validations:
      required: true
  - type: textarea
    attributes:
      label: 問題
      description: 現在発生している問題やその背景を記載してください。
    validations:
      required: true
  - type: textarea
    attributes:
      label: 改善案
      description: 改善案を記載してください。
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: 貢献意思
      options:
        - label: このIssueを解決するPull Requestの作成を自身で希望する場合はチェックしてください。
          required: false
