name: ✨ 翻訳ドキュメントの新規追加の提案
description: 翻訳ドキュメントの新規追加を提案するIssueを作成します。
labels:
  - translation
  - enhancement
body:
  - type: markdown
    attributes:
      value: 翻訳ドキュメントの新規追加をご提案いただきありがとうございます。[Issueを作成する前に同様のIssueが既に存在しないかを確認してください。](https://github.com/typst-jp/typst-jp.github.io/issues?q=is%3Aopen)
  - type: textarea
    attributes:
      label: 対象ドキュメント
      description: 翻訳対象のドキュメントを記載してください。
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: 貢献意思
      options:
        - label: このIssueを解決するPull Requestの作成を自身で希望する場合はチェックしてください。
          required: false
