use crate::foundations::{Str, func};

<<<<<<< HEAD
/// ダミーテキストの作成。
///
/// この関数は与えられた単語数だけラテン語風のダミーテキストである_Lorem Ipsum_を生成します。
/// この関数で生成される単語の並びは常に同じですが、その並び自体はランダムに選ばれています。
/// 通常のダミーテキストと同様に、意味のないテキストです。
/// レイアウトを試すプレースホルダーとして使用してください。
///
/// # 例
=======
/// Creates blind text.
///
/// This function yields a Latin-like _Lorem Ipsum_ blind text with the given
/// number of words. The sequence of words generated by the function is always
/// the same but randomly chosen. As usual for blind texts, it does not make any
/// sense. Use it as a placeholder to try layouts.
///
/// # Example
>>>>>>> eb2027e55f17a91cc2025c7a71674a2c5ea3a363
/// ```example
/// = Blind Text
/// #lorem(30)
///
/// = More Blind Text
/// #lorem(15)
/// ```
#[func(keywords = ["Blind Text"])]
pub fn lorem(
<<<<<<< HEAD
    /// ダミーテキストの単語数。
=======
    /// The length of the blind text in words.
>>>>>>> eb2027e55f17a91cc2025c7a71674a2c5ea3a363
    words: usize,
) -> Str {
    lipsum::lipsum(words).replace("--", "–").into()
}
