# Based on ripgrep's release action:
# https://github.com/BurntSushi/ripgrep/blob/master/.github/workflows/release.yml

name: CI/CD for Documentation
on: [push, pull_request]
permissions:
  contents: write
jobs:
  build-and-deploy:
    name: build-and-deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: '1.77'
      - uses: Swatinem/rust-cache@v2
      # python3 and package jinja2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: python3 -m pip install jinja2 PyYAML
      - run: cargo test --package typst-docs --lib -- tests::test_docs --exact --nocapture
      - run: python3 ./gen.py
      # deploy ./dist to https://github.com/typst-doc-cn/typst-doc-cn.github.io
      - name: Deploy
        if: github.ref == 'refs/heads/main'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist # The folder the action should deploy.
