# Based on ripgrep's release action:
# https://github.com/BurntSushi/ripgrep/blob/master/.github/workflows/release.yml

name: CI/CD for Documentation
on: [push, pull_request]
permissions:
  contents: write
jobs:
  build-and-deploy:
    name: build-and-deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: '1.77'
      - uses: Swatinem/rust-cache@v2
      - uses: jdx/mise-action@v2
      - run: uv sync --locked
      - run: mise run generate-docs
      - run: mise run generate-web
      # deploy ./dist to https://github.com/typst-doc-cn/typst-doc-cn.github.io
      - name: Deploy
        if: github.ref == 'refs/heads/main'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist # The folder the action should deploy.
